---
title: "specific variables selection"
author: "Chupeng Yue"
date: "2023-05-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#import dataset
```{r}
library(readr)
sample<-read_csv("general_sample_result.csv")
high<-read_csv("v_tan_500km_s-result.csv") #import dataset
```
#create the varibale we want to analyze
```{r}
sample$v_tan <- sample$r_med_geo * sin(sample$pm/1000*pi/648000) * 978462
high$v_tan <- high$r_med_geo * sin(high$pm/1000*pi/648000) * 978462
high$Gmag_abs <- high$phot_g_mean_mag - 5 * log10(high$r_med_geo) + 5
sample$Gmag_abs <- sample$phot_g_mean_mag - 5 * log10(sample$r_med_geo) + 5
high$RPmag_abs <- high$phot_rp_mean_mag - 5 * log10(high$r_med_geo) + 5
sample$RPmag_abs <- sample$phot_rp_mean_mag - 5 * log10(sample$r_med_geo) + 5
high$BPmag_abs <- high$phot_bp_mean_mag - 5 * log10(high$r_med_geo) + 5
sample$BPmag_abs <- sample$phot_bp_mean_mag - 5 * log10(sample$r_med_geo) + 5
```




#merge data by group 
```{r}
sample$group<-"general"
high$group<-"high"
data_final<-rbind(sample, high)
```

```{r}
data_sp<-subset(data_final,select=c(l, b, Gmag_abs, RPmag_abs, BPmag_abs, bp_rp,bp_g,g_rp, mh_msc, ebpminrp_gspphot...149,ebpminrp_gspphot...192, teff_gspphot...131,teff_gspphot...168,logg_gspphot...134,logg_gspphot...171,alphafe_gspspec,fem_gspspec,sife_gspspec,cafe_gspspec,feiim_gspspec))
```

```{r}
library(Boruta)
library(caret)
library(randomForest)
```
#random forest 
```{r}
set.seed(111)
model <- randomForest(bp_rp ~ .,data = data_sp,importance=TRUE,na.action=na.roughfix)#use roughfix to replace na value and get the model
```

```{r}
importance(model)
varImpPlot(model)
```


