---
title: "Gaia DR3 High Velocity"
author: "s"
# date: "today"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
knitr::opts_chunk$set(warning = F, results = "markup", message = F)
# knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times

# The package "ezids" (EZ Intro to Data Science) includes a lot of the helper functions we developed for the course. 
# Some of the frequently used functions are loadPkg(), xkabledply(), xkablesummary(), uzscale(), etc.
library(ezids)
library(ggplot2)
library(plotly)
library(htmlwidgets)
# library(patchwork)
# setwd("./GAIA-DR3-DATS6101/") 
```

```{r}
df_general <- read.csv("general_sample_result.csv")
df_general$sample <- "General Sample"
df_high <- read.csv("v_tan_500km_s-result.csv")
df_high$sample <- "High Velocity Sample"
df <- rbind(df_general, df_high)

# calculate tangential velocity r_med_geo*sin(pm/1000*PI()/648000) * 978462
df$v_tan <- df$r_med_geo * sin(df$pm/1000*pi/648000) * 978462

# calculate absolute magnitudes from r_med_geo distance
df$Gmag_abs <- df$phot_g_mean_mag - 5 * log10(df$r_med_geo) + 5
df$RPmag_abs <- df$phot_rp_mean_mag - 5 * log10(df$r_med_geo) + 5
df$BPmag_abs <- df$phot_bp_mean_mag - 5 * log10(df$r_med_geo) + 5
```

```{r}
# columns of data
colnames(df)
```


```{r}
# print mean of mh_msc for the two samples
mean(df_general$mh_msc, na.rm = T)
mean(df_high$mh_msc, na.rm = T)

# print number of non-NA values in mh_msc for the two samples
sum(!is.na(df_general$mh_msc))
sum(!is.na(df_high$mh_msc))

# compare differences in mh_msc between the two samples
t.test(df_general$mh_msc, df_high$mh_msc, var.equal = F)
t.test(df_general$age_flame, df_high$age_flame, var.equal = F)

# make histogram of mh_msc for the two samples, normalize to  frequency
hist <- ggplot(df, aes(x=mh_msc, fill=sample)) + 
  geom_histogram(aes(y=..density..), position="identity", alpha=0.5, bins=50) + 
  scale_fill_manual(values=c("red", "blue"), name='Sample',) + 
  theme_bw() + 
  labs(x="MH_MSC", y="Frequency")

ggplotly(hist)

# save plotly figure
p <- ggplotly(hist)
htmlwidgets::saveWidget(p, "hist.html")
# also save as png
ggsave("mh_hist.png", width=8, height=6, units="in", dpi=300)
```

```{r}
t.test(df_general$r_med_geo, df_high$r_med_geo, var.equal = F)

# histogram of distance
hist <- ggplot(df, aes(x=r_med_geo, fill=sample)) + 
  geom_histogram(aes(y=..density..), position="identity", alpha=0.5, bins=50) + 
  scale_fill_manual(values=c("red", "blue"), name='Sample',) + 
  theme_bw() + 
  labs(x="Distance (pc)", y="Frequency")

ggplotly(hist)

# save as png
ggsave("dist_hist.png", width=8, height=6, units="in", dpi=300)
```

```{r}
# histogram of galactic latitude
hist <- ggplot(df, aes(x=b, fill=sample)) + 
  geom_histogram(aes(y=..density..), position="identity", alpha=0.5, bins=50) + 
  scale_fill_manual(values=c("red", "blue"), name='Sample',) + 
  theme_bw() + 
  labs(x="Galactic Latitude (b)", y="Frequency")

ggsave("b_hist.png", width=8, height=6, units="in", dpi=300)

```

```{r}
# number of empty values in ebpminrp_gspphot
sum(is.na(df_general$ebpminrp_gspphot))
sum(is.na(df_high$ebpminrp_gspphot))

# histogram of E(BP-RP) extinction
hist <- ggplot(df, aes(x=ebpminrp_gspphot, fill=sample)) + 
  geom_histogram(aes(y=..density..), position="identity", alpha=0.5, bins=50) + 
  scale_fill_manual(values=c("red", "blue"), name='Sample',) + 
  theme_bw() + 
  labs(x="E(BP-RP)", y="Frequency")

ggsave("ebp-rp_hist.png", width=8, height=6, units="in", dpi=300)

```

```{r}
# make Gaia CMD of high velocity and general sample stars using phot_g_mean_mag and bp_rp columns using plotly. overlay the two CMDs on the same plot.
cmd <- ggplot(df, aes(x=bp_rp, y=Gmag_abs, text=paste('designation: ', designation))) + 
  geom_point(aes(color=sample), alpha=0.25, ) + 
  scale_color_manual(values=c("red", "blue"), name='Sample') + 
  # invert y axis
  scale_y_reverse() +
  theme_bw() + 
  labs(x="BP-RP", y="G")

# ggplotly(cmd)

# save plotly figure
p <- ggplotly(cmd)
htmlwidgets::saveWidget(p, "cmd.html")
# also save as png
ggsave("cmd.png", width=8, height=6, units="in", dpi=300)
```

```{r}
# correct color for extinction
df$bp_rp_corr <- df$bp_rp - df$ebpminrp_gspphot
# correct Gmag for extinction based on A_G = 2 * E(BP-RP)
df$Gmag_abs_corr <- df$Gmag_abs - 2 * df$ebpminrp_gspphot

cmd_corr <- ggplot(df, aes(x=bp_rp_corr, y=Gmag_abs_corr, text=paste('designation: ', designation))) + 
  geom_point(aes(color=sample), alpha=0.25, ) + 
  scale_color_manual(values=c("red", "blue"), name='Sample') + 
  # invert y axis
  scale_y_reverse() +
  theme_bw() + 
  labs(x="BP-RP Dereddened", y="G")

# ggplotly(cmd)

# save plotly figure
p <- ggplotly(cmd_corr)
htmlwidgets::saveWidget(p, "cmd_corr.html")
# also save as png
ggsave("cmd_corr.png", width=8, height=6, units="in", dpi=300)
```

```{r}
# make color-color diagram with bp-gp and gp-rp
ccd <- ggplot(df, aes(x=bp_rp, y=bp_g)) + 
  geom_point(aes(color=sample), alpha=0.25) + 
  scale_color_manual(values=c("red", "blue"), labels=c("General Sample", "High Velocity Sample")) + 
  theme_bw() + 
  labs(x="BP-RP", y="RP-RP")

# ggplotly(ccd)

# save plotly figure
p <- ggplotly(ccd)
htmlwidgets::saveWidget(p, "ccd.html")
# also save as png
ggsave("ccd.png", width=8, height=6, units="in", dpi=300)
```


```{r}
# select stars with Gmag_abs between 4 and 9, and bp_rp between 0.5 and 2.0

df_ms <- df %>% filter(Gmag_abs > 4 & Gmag_abs < 9 & bp_rp > 0.5 & bp_rp < 2.0)

# linear regression of bp_rp vs Gmag_abs on df_ms
fit <- lm(Gmag_abs ~ bp_rp, data=df_ms)
summary(fit)

# test the effect of sample on the regression
fit2 <- lm(Gmag_abs ~ bp_rp + sample, data=df_ms)
summary(fit2)

# test the effect of the interaction between sample and bp_rp on the regression
fit3 <- lm(Gmag_abs ~ bp_rp * sample, data=df_ms)
summary(fit3)

# do anova test on fit2 vs fit, and fit3 vs fit2
anova(fit2, fit)
anova(fit3, fit2)

```
  
```{r}

# plot the regression line for each sample on cmd
cmd_ms1 <- ggplot(df_ms, aes(x=bp_rp, y=Gmag_abs)) + 
  geom_point(aes(color=sample), alpha=0.25) + 
  scale_color_manual(values=c("red", "blue"), name='Sample',) + 
  theme_bw() + 
  labs(x="BP-RP", y="G") + 
  geom_abline(aes(intercept=fit3$coefficients[1], slope=fit3$coefficients[2]), color="blue")
  # invert y axis
  # scale_y_reverse()


# ggplotly(cmd_ms1)

# save plotly figure
p <- ggplotly(cmd_ms1)
htmlwidgets::saveWidget(p, "cmd_ms1.html")
# also save as png
ggsave("cmd_ms1.png", width=8, height=6, units="in", dpi=300)
```
```{r}

# plot the regression line for each sample on cmd
cmd_ms2 <- ggplot(df_ms, aes(x=bp_rp, y=Gmag_abs)) + 
  geom_point(aes(color=sample), alpha=0.25) + 
  scale_color_manual(values=c("red", "blue"), name='Sample',) + 
  theme_bw() + 
  labs(x="BP-RP", y="G") + 
  geom_abline(aes(intercept=fit2$coefficients[1], slope=fit2$coefficients[2]), color="red") + 
  geom_abline(aes(intercept=fit2$coefficients[1]+fit2$coefficients[3], slope=fit2$coefficients[2]), color="blue") 
  # invert y axis
  # scale_y_reverse()


# ggplotly(cmd_ms2)

# save plotly figure
p <- ggplotly(cmd_ms2)
htmlwidgets::saveWidget(p, "cmd_ms2.html")
# also save as png
ggsave("cmd_ms2.png", width=8, height=6, units="in", dpi=300)
```
```{r}

# plot the regression line for each sample on cmd
cmd_ms3 <- ggplot(df_ms, aes(x=bp_rp, y=Gmag_abs)) + 
  geom_point(aes(color=sample), alpha=0.25) + 
  scale_color_manual(values=c("red", "blue"), name='Sample',) + 
  theme_bw() + 
  labs(x="BP-RP", y="G") + 
  geom_abline(aes(intercept=fit3$coefficients[1], slope=fit3$coefficients[2]), color="red", ) +
  geom_abline(aes(intercept=fit3$coefficients[1]+fit3$coefficients[3], slope=fit3$coefficients[2] + fit3$coefficients[4]), color="blue")
  # invert y axis
  # scale_y_reverse()


# ggplotly(cmd_ms2)

# save plotly figure
p <- ggplotly(cmd_ms3)
htmlwidgets::saveWidget(p, "cmd_ms3.html")
# also save as png
ggsave("cmd_ms3.png", width=8, height=6, units="in", dpi=300)
```

```{r}
# select sources with bp_rp < 0

df_blue <- df %>% filter(bp_rp < 0)

# view the data
View(df_blue)

```


